language: java

install: gradle -c settings-travis-ci.gradle -PBINTRAY_USER=nope -PBINTRAY_API_KEY=doublenope assemble

script: gradle -c settings-travis-ci.gradle -PBINTRAY_USER=nope -PBINTRAY_API_KEY=doublenope check

before_cache:
    - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
    - rm -rf $HOME/.gradle/caches/*/plugin-resolution/

cache:
    directories:
        - $HOME/.gradle/caches/
        - $HOME/.gradle/wrapper/

