language: android
jdk: oraclejdk8

install: gradle --version

script: gradle check -c settings-travis-ci.gradle -PBINTRAY_USER=nope -PBINTRAY_API_KEY=doublenope

before_cache:
    - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
    - rm -rf $HOME/.gradle/caches/*/plugin-resolution/

cache:
    directories:
        - $HOME/.gradle/caches/
        - $HOME/.gradle/wrapper/

