package ph.codeia.processor;

import java.text.SimpleDateFormat;
import java.util.Locale;

import ph.codeia.values.Do;

/**
 * This file is a part of the vanilla project.
 */

public final class Util {

    static final String SIGNATURE = ""
            + "Generated by vanilla-processor\n"
            + "https://github.com/monzee/vanilla.git\n";

    static final SimpleDateFormat ISO_DATE_FORMAT = new SimpleDateFormat(
            "yyyy-MM-dd'T'HH:mm:ss.SSSZ",
            Locale.US);

    static <T> boolean forSome(T nullable, Do.Just<T> fun) {
        if (nullable != null) {
            fun.got(nullable);
            return true;
        }
        return false;
    }

    static String quote(String identifier) {
        return "\"" + identifier.replace("\"", "\"\"") + "\"";
    }

    private Util() {}

}
